# Task 1

## 1.

In [1]:
def divide_zero():
    try:
        return 5/0
    except:
        return "Cannot divide a number with zero"

    
f=divide_zero()
print(f)

Cannot divide a number with zero


## 2

In [5]:
def sentence_generator(L_sub,L_verb,L_obj):
    counter = 0
    for i in L_sub:
        for j in L_verb:
            for k in L_obj:
                counter=counter+1 
                if(counter ==1):
                    out_str = i+' '+j+' '+k
                else:
                    out_str = out_str + '\n'+i+' '+j+' '+k
    return out_str

k=sentence_generator(["Americans ","Indians"],["play","watch"],["Baseball","Cricket"])
print(k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

## 1

In [22]:
import numpy as np
def get_vander(L):
    N=len(L)
    lst_matrix=[]
    for val in L:
        lst=[]
        for i in range(N):
            lst.append((val**(N-i-1)))
        lst_matrix.append(lst)
    return np.matrix(lst_matrix)

qq=get_vander([1,2,3,5])
print(qq)
    

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [20]:
a = np.matrix([[1, 2], [3, 4]])  # using array of array
print('2x2 matrix is:\n', a)

2x2 matrix is:
 [[1 2]
 [3 4]]
